book/urls.py
from django.conf.urls import url 
from book import views
from django.urls import path 
from forward.settings import DEBUG, STATIC_URL, STATIC_DIR, MEDIA_URL,MEDIA_ROOT
from django.conf.urls.static import static

urlpatterns=[
    path('',views.index, name='index'),
    path('create/',views.create, name='create-book'),
    path('update/<int:book_id>',views.update_book),
    path('delete/<int:book_id>',views.delete_book)
    # MEDIA
]

forward/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from hello_world import views
from forward.settings import DEBUG, STATIC_URL, STATIC_DIR, MEDIA_URL,MEDIA_ROOT
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^book/',include('book.urls')),
    url(r'^hello_world/',include('hello_world.urls')),
    url(r'^combine/',include('combine.urls')),
    url(r'^logout/$',views.user_logout, name='logout')
]

hello_world/urls.py
from django.conf.urls import url 
from hello_world import views

app_name = 'hello_world'

urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^dashboard/$',views.dashboard,name='dashboard'),
]

hello_world/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    occupation = models.TextField(blank=True)
    company=models.TextField(blank=True)
    hobby=models.TextField(blank=True)

    def __str__(self):
        return self.user.username

hello_world/forms.py
from django import forms 
from hello_world.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
        widgets = {
            'username':forms.TextInput(attrs={'class':'form-control','placeholder': 'Enter your username'}),
            'password':forms.PasswordInput(attrs={'class':'form-control'}),
            'email':forms.TextInput(attrs={'class':'form-control'}),
        }

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('occupation','company','hobby')
        widgets = {
            'occupation':forms.Textarea(attrs={'class':'form-control'}),
            'company':forms.Textarea(attrs={'class':'form-control'}),
            'hobby':forms.Textarea(attrs={'class':'form-control'}),
        }

hello_world/views.py
from django.shortcuts import render
from hello_world.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from hello_world.models import UserProfileInfo

# Create your views here.
def index(request):
    return render(request,'hello_world/index.html')

@login_required
def special(request):
    all_users = UserProfileInfo.objects.select_related('user')
    # for user in all_users:
    #     print(user)
    return HttpResponse(all_users[0].occupation)

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user=user
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else: # if GET request
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    
    return render(request,'hello_world/registration.html',
    {'user_form':user_form,
    'profile_form':profile_form,
    'registered':registered}
    )

def user_login(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request,'hello_world/login.html')

# READ
def dashboard(request):
    all_users = UserProfileInfo.objects.select_related('user')
    return render(request,'hello_world/dashboard.html',{'all_users':all_users})

# # UPDATE
# def user_login(request):
#     all_users = Entry.objects.all()
#     return render(request,'hello_world/dashboard.html')

# # DELETE
# def user_login(request):
#     all_users = Entry.objects.all()
#     return render(request,'hello_world/dashboard.html')

templates/hello_world/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'hello_world:register' %}">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'hello_world:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/hello_world/index.html
{% extends "hello_world/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Forward School !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/hello_world/login.html
{% extends 'hello_world/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'hello_world:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
          <label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

templates/hello_world/registration.html
{% extends "hello_world/base.html" %}
{% load static %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}