book/urls.py
from django.conf.urls import url 
from book import views
from django.urls import path 
from forward.settings import DEBUG, STATIC_URL, STATIC_DIR, MEDIA_URL,MEDIA_ROOT
from django.conf.urls.static import static

urlpatterns=[
    path('',views.index, name='index'),
    path('create/',views.create, name='create-book'),
    path('update/<int:book_id>',views.update_book),
    path('delete/<int:book_id>',views.delete_book)
    # MEDIA
]

combine/urls.py
from django.conf.urls import url 
from combine import views
from django.urls import path 
from django.conf.urls.static import static

app_name = 'combine'

urlpatterns=[
    path('',views.HomePageView.as_view(), name='home'),
    path('getnum/',views.Api.getNums, name='get-num'),
    path('getavg/',views.Api.getAvg, name='get-avg'),
    path('geimage/',views.Api.getImage, name='get-graph'),
    path('getdata/',views.Api.getData, name='get-data'),
    path('get-seaborn-graph/',views.Api.getSeabornGraph, name='get-seaborn-graph'),
    path('chart/',views.HomeView.as_view(), name='home-view'),
    path('chart-api/',views.ChartData.as_view(), name='chart-api'),
    path('plotly-chart/',views.PlotlyChartView.as_view(), name='plotly-chart'),
    path('book-table/',views.BookTableView.as_view()),
    path('user-table/',views.UserTableView.as_view())
]

forward/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from hello_world import views
from forward.settings import DEBUG, STATIC_URL, STATIC_DIR, MEDIA_URL,MEDIA_ROOT
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^book/',include('book.urls')),
    url(r'^hello_world/',include('hello_world.urls')),
    url(r'^combine/',include('combine.urls')),
    url(r'^logout/$',views.user_logout, name='logout')
]

combine/models.py
from django.db import models

# Create your models here.

combine/views.py
from django.shortcuts import render
from django.http import HttpResponse
from forward.settings import MEDIA_URL,MEDIA_ROOT
from django.conf.urls.static import static
from django.views.generic import TemplateView, View 

import numpy as np
import pandas as pd
import matplotlib as pl
pl.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sb

class HomePageView(TemplateView):
    def get(self,request,**kwargs):
        return render(request, 'combine/index.html', context=None)

class Api(TemplateView):
    # Create your views here.
    def getNums(request):
        n = np.array([2,3,4])
        name1 = "name-1" + str(n[1])
        return HttpResponse('{"name:":'+name1+',"age":31,"city":"New York"}')

    def getAvg(request):
        s1=request.GET.get("val","")
        if len(s1)==0:
            return HttpResponse("none")
        l1=s1.split(',')
        ar=np.array(l1,dtype=int)

        return HttpResponse(str(np.average(ar)))

    def getImage(request):
        x = np.arange(0,2 * np.pi, 0.01)
        s = np.cos(x)**2
        plt.plot(x,s)

        plt.xlabel('xlabel(X)')
        plt.ylabel('ylabel(y)')
        plt.title('Basic Graph!')
        plt.grid(True)

        response = HttpResponse(content_type="image/jpeg")
        plt.savefig(response, format="png")
        return response

    def getData(request):
        samp = np.random.randint(100,600,size=(4,5))
        df = pd.DataFrame(samp, index=['alex','danny','lina','david'],columns=['Jan','Feb','Mar','Apr','May'])
        return HttpResponse(df.to_html(classes='table table-bordered'))

    def getSeabornGraph(request):
        file_path = MEDIA_ROOT+"/data/titanic_train.csv"
        df = pd.read_csv(file_path)
        graph = sb.factorplot(x='Survived',hue='Sex',data=df, col='Pclass',kind='count')
        response = HttpResponse(content_type="image/jpeg")
        graph.savefig(response, format="png")
        return response

# Part 2: CHART.JS (Involves Javascript)
from rest_framework.views import APIView
from rest_framework.response import Response

class HomeView(TemplateView):
    def get(self, request, *args, **kwargs):
        return render(request, 'combine/charts.html')

class ChartData(APIView):
    authentication_classes=[]
    permission_classes=[]

    def get(self, request, format=None):
        labels=['January','February',"March","April","May","June","July"]
        chartLabel="My Data"
        chartData=[0,10,5,2,20,30,45]
        data = {
            "labels":labels, 
            "chartLabel":chartLabel, 
            "chartdata":chartData, 
        }
        return Response(data)

# Part 3: Plot.ly (Does not involves Javascript)
from plotly.offline import plot
import plotly.graph_objs as go

class PlotlyChartView(TemplateView):
    def get(self, request, *args, **kwargs):
        x_data=[0,1,2,3]
        y_data=[x**2 for x in x_data]
        plot_div = plot([go.Scatter(
            x=x_data,
            y=y_data,
            mode='lines',
            name='My Plotly Chart',
            opacity=0.8,
            marker_color='green'
        )], output_type='div')

        return render(request, 'combine/plotly.html', context={'plot_div':plot_div})

# Part 4: Plotly Dash (Does not involves Javascript)

# Part 5: Datatables 
import django_tables2 as tables
from book.models import Book
from hello_world.models import User, UserProfileInfo

# Table Class
class BookTable(tables.Table):
    class Meta:
        model = Book
        attrs = {"class": "table-bordered"}

# View
class BookTableView(tables.SingleTableView):
    table_class=BookTable
    queryset=Book.objects.all()
    template_name="combine/table.html"

# Table Class
class UserTable(tables.Table):
    class Meta:
        model = UserProfileInfo
        attrs = {"class": "table-bordered"}

# View
class UserTableView(tables.SingleTableView):
    table_class=UserTable
    # queryset=UserProfileInfo.objects.select_related('user')
    queryset=UserProfileInfo.objects.all()
    template_name="combine/table.html"

templates/combine/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="#">DJANGO</a></li>
          <li><a class="navbar-link" href="#">Admin</a></li>
          <li><a class="navbar-link" href="#">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="#">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div style="text-align:center">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

templates/combine/charts.html
{% extends "combine/base.html" %}
{% block body_block %}
<div class="container-fluid">
    <center class="row">
        <h2>Our Implementation of <b>Chart.js</b> in Django</h2>
    </center>
    <hr>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <canvas id="myChartLine"></canvas>
        </div>
        <div class="col-md-3"></div>
    </div>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <canvas id="myChartBar"></canvas>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
 <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script> 
<script>
    // Make API calls
    $.ajax({
        method: "GET",
        url: "{% url 'combine:chart-api' %}",
        success: function(data){
            drawLineGraph(data,'myChartLine');
            drawBarGraph(data,'myChartBar');
        },
        error: function(err){
            console.log(err);
        }
    })

    function drawLineGraph(data, id) { 
      var labels = data.labels; 
      var chartLabel = data.chartLabel; 
      var chartdata = data.chartdata; 
      var ctx = document.getElementById(id).getContext('2d'); 
      var chart = new Chart(ctx, { 
        // The type of chart we want to create 
        type: 'line', 
  
        // The data for our dataset 
        data: { 
          labels: labels, 
          datasets: [{ 
            label: chartLabel, 
            backgroundColor: 'rgb(255, 100, 200)', 
            borderColor: 'rgb(55, 99, 132)', 
            data: chartdata, 
          }] 
        }, 
  
        // Configuration options go here 
        options: { 
          scales: { 
            xAxes: [{ 
              display: true 
            }], 
            yAxes: [{ 
              ticks: { 
                beginAtZero: true 
              } 
            }] 
          } 
        } 
  
      }); 
    } 
  
    function drawBarGraph(data, id) { 
      var labels = data.labels; 
      var chartLabel = data.chartLabel; 
      var chartdata = data.chartdata; 
      var ctx = document.getElementById(id).getContext('2d'); 
      var myChart = new Chart(ctx, { 
        type: 'bar', 
        data: { 
          labels: labels, 
          datasets: [{ 
            label: chartLabel, 
            data: chartdata, 
            backgroundColor: [ 
              'rgba(255, 99, 132, 0.2)', 
              'rgba(54, 162, 235, 0.2)', 
              'rgba(255, 206, 86, 0.2)', 
              'rgba(75, 192, 192, 0.2)', 
              'rgba(153, 102, 255, 0.2)', 
              'rgba(255, 159, 64, 0.2)' 
            ], 
            borderColor: [ 
              'rgba(255, 99, 132, 1)', 
              'rgba(54, 162, 235, 1)', 
              'rgba(255, 206, 86, 1)', 
              'rgba(75, 192, 192, 1)', 
              'rgba(153, 102, 255, 1)', 
              'rgba(255, 159, 64, 1)' 
            ], 
            borderWidth: 1 
          }] 
        }, 
        options: { 
          scales: { 
            yAxes: [{ 
              ticks: { 
                beginAtZero: true 
              } 
            }] 
          } 
        } 
      }); 
    }
</script>
{% endblock %}

templates/combine/index.html
{% extends "combine/base.html" %}
{% block body_block %}
<div style="text-align:center">
  <h1>
    Welcome to {{title}}!
  </h1>
    <div class="container-fluid">
        <div class="row">
            <div class="col-3">
            <button onclick="click1()" >click me</button>
            </div>
            <div class="col-9">
            <span style="background-color:red" id="customer"></span>
            </div>
        <div>
        <div class="row">
            <div class="col-3">
            <button onclick="getavg()">Get Average</button>
            </div>
            <div class="col-9" style="text-align:center">
            <input id="avg" type="text">
            <label>Result:</label>
            <span id="avg_res">
            </div>
        <div>
        <div class="row">
            <div class="col-3">
            <button onclick="getimage()">load graph</button>
            </div>
            <div class="col-9">
                <img id="matplotlib" width="500">
            </div>
        <div>
        <div class="row">
            <div class="col-3">
            <button onclick="getPandas()">load table</button>
            </div>
            <div id="pandas" class="col-9">
            </div>
        <div>
        <div class="row">
            <div class="col-3">
            <button onclick="getSBimage()">seaborn graph</button>
            </div>
            <div class="col-9">
                <img id="seaborn" width="1000">
            </div>
        <div>
    </div>
</div>
<script>
    // Make API calls
    function click1() {
		fetch('{% url 'combine:get-num' %}')
		.then(res => res.text())
		.then(data => document.getElementById('customer').innerHTML = data)
	}

    function getavg() {
        var val_list = document.getElementById('avg').value;
		fetch('{% url 'combine:get-avg' %}'+"?val="+val_list)
		.then(res => res.text())
		.then(data => document.getElementById('avg_res').innerHTML = data)
	}

    function getimage() {
		fetch('{% url 'combine:get-graph' %}')
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('matplotlib').src = imgURL
        })
	}

    function getPandas() {
		fetch('{% url 'combine:get-data' %}')
		.then(res => res.text())
		.then(data => document.getElementById('pandas').innerHTML = data)
	}

    function getSBimage() {
		fetch('{% url 'combine:get-seaborn-graph' %}')
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('seaborn').src = imgURL
        })
	}
    
</script>
{% endblock %}

templates/combine/plotly.html
{% extends "combine/base.html" %}
{% block body_block %}
<div class="container-fluid">
    <center class="row">
        <h2>Our Implementation of <b>Plot.ly</b> in Django</h2>
    </center>
    <hr>
    {% autoescape off %}
    {{ plot_div }}
    {% endautoescape %}
</div>
{% endblock %}

templates/combine/table.html
{% extends "combine/base.html" %}
{% block body_block %}
<div class="container-fluid">
    <center class="row">
        <h2>Our Implementation of Django Tables</h2>
    </center>
    <center class="row">
        {% load django_tables2 %}
        {% render_table table %}
    </center>
    <hr>
    
</div>
{% endblock %}